(set-language-environment 'Japanese)
(set-language-environment  'utf-8)
(prefer-coding-system 'utf-8)

(global-unset-key "\C-q")
(global-set-key (kbd "C-h") 'delete-backward-char)
(global-set-key (kbd "C-c C-h") 'help-command)

(global-set-key (kbd "C-q -")  'split-window-vertically)
(global-set-key (kbd "C-q |")  'split-window-horizontally)
(global-set-key (kbd "C-q x")  'delete-window)
(global-set-key (kbd "C-q c")  'make-frame-command)
(global-set-key (kbd "C-q n")  'other-frame)
(global-set-key (kbd "C-q C-b")  'windmove-left)
(global-set-key (kbd "C-q C-n")  'windmove-down)
(global-set-key (kbd "C-q C-p")  'windmove-up)
(global-set-key (kbd "C-q C-f") 'windmove-right)
(global-set-key "\M-n" (kbd "C-u 5 C-n"))
(global-set-key "\M-p" (kbd "C-u 5 C-p"))

(menu-bar-mode -1)
(setq initial-scratch-message nil)
(setq inhibit-startup-message t)
(setq scroll-conservatively 1)
(setq default-tab-width 4)
(setq make-backup-files nil)
(setq auto-save-default nil)
(column-number-mode t)
(global-linum-mode t)
(set-face-attribute 'linum nil
            :foreground "yellow1"
            :height 0.9)
(show-paren-mode t)
(set-face-background 'show-paren-match nil)
(set-face-attribute 'show-paren-match nil
                    :inherit 'highlight)

(set-face-foreground 'default "white")
(set-face-background 'default "black")
(set-face-foreground 'font-lock-type-face "green1")
(set-face-foreground 'font-lock-variable-name-face "white")
(set-face-foreground 'font-lock-function-name-face "yellow1")
(set-face-foreground 'font-lock-builtin-face "magenta1")
(set-face-foreground 'font-lock-keyword-face "cyan1")
(set-face-foreground 'font-lock-string-face "red1")
(set-face-foreground 'font-lock-comment-face "green1")
(set-face-foreground 'font-lock-constant-face "cyan1")
(set-face-foreground 'font-lock-warning-face "violet")

(when (eq system-type 'darwin)
	  (defun copy-from-darwin ()
	    (shell-command-to-string "pbpaste"))
	  (defun paste-to-darwin (text &optional push)
	    (let ((process-connection-type nil))
	      (let ((proc (start-process "pbcopy" "*Messages*" "pbcopy")))
		(process-send-string proc text)
		(process-send-eof proc))))
	  (setq interprogram-cut-function 'paste-to-darwin)
	  (setq interprogram-paste-function 'copy-from-darwin)
	  )

(when (eq system-type 'gnu/linux)
  (setq x-select-enable-clipboard t)
  (defun xsel-cut-function (text &optional push)
    (with-temp-buffer
      (insert text)
      (call-process-region (point-min) (point-max) "xsel" nil 0 nil "--clipboard" "--input"))
  (defun xsel-paste-function()
    (let ((xsel-output (shell-command-to-string "xsel --clipboard --output")))
      (unless (string= (car kill-ring) xsel-output)
	xsel-output )))
  (setq interprogram-cut-function 'xsel-cut-function)
  (setq interprogram-paste-function 'xsel-paste-function))
)
