(set-language-environment 'Japanese)
(set-language-environment  'utf-8)
(prefer-coding-system 'utf-8)

(global-unset-key "\C-q")
(global-set-key (kbd "C-h") 'delete-backward-char)

(global-set-key (kbd "C-q -")  'split-window-vertically)
(global-set-key (kbd "C-q |")  'split-window-horizontally)
(global-set-key (kbd "C-q x")  'delete-window)
(global-set-key (kbd "C-q c")  'make-frame-command)
(global-set-key (kbd "C-q n")  'other-frame)
(global-set-key (kbd "C-q C-b")  'windmove-left)
(global-set-key (kbd "C-q C-n")  'windmove-down)
(global-set-key (kbd "C-q C-p")    'windmove-up)
(global-set-key (kbd "C-q C-f") 'windmove-right)

(column-number-mode t)
(global-linum-mode t)
(display-time)
(setq initial-scratch-message nil)
(setq scroll-conservatively 1)
(setq inhibit-startup-message t)
(setq default-tab-width 4)
(setq make-backup-files nil)
(setq auto-save-default nil)
(menu-bar-mode -1)

(set-face-foreground 'default "white")
(set-face-background 'default "black")
;(set-face-background 'default "#303030")
(set-face-foreground 'font-lock-keyword-face "cyan")
(set-face-foreground 'font-lock-function-name-face "yellow")
(set-face-foreground 'font-lock-string-face "red")
(set-face-foreground 'font-lock-comment-face "green")
;(set-face-foreground 'font-lock-builtin-face "yellow1")
;(set-face-foreground 'font-lock-variable-name-face "WhiteSmoke")
;(set-face-foreground 'font-lock-type-face "green1")
;(set-face-foreground 'font-lock-constant-face "cyan1")
;(set-face-foreground 'font-lock-warning-face "violet")
(show-paren-mode t)
(set-face-background 'show-paren-match nil)
(set-face-attribute 'show-paren-match nil
                    :inherit 'highlight)
